### ISSUE TITLE
Encoding Error When Migrating DB

### ISSUE THREAD

**Issue by jessebake** [piggybak/piggybak#81]
Hi, 
I ran the Piggybak install command which worked fine as far as I recall, but when I try to run rake db:migrate on my app I am getting the following error:

Mysql2::Error: Incorrect string value: '\xC4\x81n' for column 'abbr' at row 1: INSERT INTO
`states` (`abbr`, `country_id`, `name`) VALUES ('\'Ajman', 8, 'AJ')
 
I'm somewhat new to Ruby/Rails so if anyone has any suggestions that would be great. Also, I'm using Rails 4.1.8 and ruby 2.1.5p273 and I am trying to install Piggybak onto an existing app.

**Comment by juanroldan1989** [comment]
'\'Ajman' value seems to not be escaped properly. It might be some kind of populate trying to insert into this table

**Comment by jessebake** [comment]
First of all, thanks for the quick reply. Second of all, do you have any suggestions on which steps I should take to figure out how to remedy this? I'm not very familiar with Rails yet and if I'm right, I know that the db:migrate is populating my database with the data from the Piggybak app but I don't know where to find that data to correct it.

**Comment by juanroldan1989** [comment]
No problem mate, first let's reset the entire setup:

rake db:drop
rake db:create

Now try:

rake piggybak:install:migrations
rake db:migrate
rails generate devise:install
rails generate devise User
rake db:migrate
rails g rails_admin:install
rake db:migrate

Let's see if that does the trick. 

BTW: the steps are inside piggyback/lib/piggyback/cli.rb - I assume we already took a look into the setup steps mentioned inside repo's description: https://github.com/piggybak/piggybak#installation

**Comment by jessebake** [comment]
I followed the repos description set up files exactly. 

Doing what you said, I dropped and created the databases successfully, then did rake piggybak:install:migrations
which worked, but when I did db:migrate it gets down to here:
== 20150221035419 CreateTaxMethodValues: migrated (0.0823s) ===================

== 20150221035420 PopulateCountriesAndStates: migrating =======================

and it has been sitting there for a few minutes, which I'm guessing is not normal.

**Comment by juanroldan1989** [comment]
We're in a good path then! Populates are working now, so it's a progress.

Inspecting PopulateCountriesAndStates I found something I don't like:

line 12
ISO3166::Country.all.each do |country_array|

I don't how many countries will *ISO3166::Country* bring but all of the are being loaded in memory at the same time, that could explain the process being stuck there for some time.

Please change that line into:
ISO3166::Country.first(10).each do |country_array|

You will need to run the steps I mentioned in my previous comment again.

**Comment by jessebake** [comment]
Ok, great! After making the change, I am once again hung upon 
== 20150221035420 PopulateCountriesAndStates: migrating =======================
I guess I just need to let it run for 15 minutes or so?

If it is any help, the original error was pointing to line 20:
      iso3166_country = ISO3166::Country.new(abbr)
        iso3166_country.states.each do |key, value|
          name = key
          abbr = value["name"]
          Piggybak::State.create! :name => name, :abbr => abbr, :country => country

Line 20 is name = key

**Comment by juanroldan1989** [comment]
Well let's see what happens after a while.

If you like, please open a new tab inside terminal and type:

*tail -f log/development.log*

You should see some activity (INSERT INTO kind of actions) in the database.

**Comment by jessebake** [comment]
Thank you!

It ended up taking forever but it finally all worked! 
I'm not sure what caused the original problem, but I really appreciate the help.

**Comment by juanroldan1989** [comment]
Glad to help! :)
