### ISSUE TITLE
Country nil!

### ISSUE THREAD

**Issue by manat129** [piggybak/piggybak#83]
The country is nil when i proceed to checkout, in browser console there was an errors Uncaught TypeError: Cannot read property 'length' of undefined (piggybak.states.js?body=1:30). I was already check country in rails_admin and all countries is there. Can somebody give me some solution for this situation?

**Comment by juanroldan1989** [comment]
Hey @manat129 could you please post in some logs about this error and inside which page did you get it ?

Thanks !

**Comment by manat129** [comment]
Started GET "/checkout/orders/geodata" for 127.0.0.1 at 2015-03-26 08:35:36 +0700
Processing by Piggybak::OrdersController#geodata as JSON
  Piggybak::Country Load (1.2ms)  SELECT "piggybak_countries".* FROM "piggybak_countries"   ORDER BY name ASC
  Piggybak::State Load (13.2ms)  SELECT "piggybak_states".* FROM "piggybak_states"  WHERE "piggybak_states"."country_id" IN (3, 16,..., 250)
Completed 200 OK in 343ms (Views: 164.1ms | ActiveRecord: 14.4ms)

In page when i wanna to proceed the line_item as orders, in my case in page /checkout

**Comment by manat129** [comment]
My bad,.. I'm not set option for country Active shipping and Avtive billing "true" :)

**Comment by pmaojo** [comment]
I had the same problem couse I was making the same mistake, not allowing that options. Thanktyou.
Anyone who wants to activate all countries and states for billing and shipping: 

On terminal:

´rails c´
´Piggybak::Country.update_all(active_billing: "true")´
´Piggybak::Country.update_all(active_shipping: "true")´
