### ISSUE TITLE
Rails 4.2 - PopulateCountriesandStates Migration Error

### ISSUE THREAD

**Issue by tamizahmed** [piggybak/piggybak#84]
Hi there - I'm trying to install piggybak in my Rails 4.2.2. app, but the installation gets stalled during the migrations (details below).

I've read through a number of issues that were related to the countries migration, but none seemed to be this particular problem. Please help!

== 20150921001302 PopulateCountriesAndStates: migrating =======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `[]' for #<ISO3166::Country:0x007f91c4f5eff8>/.../db/migrate/20150921001302_populate_countries_and_states.piggybak.rb:14:in `block in up'

**Comment by AToner** [comment]
Looks like the countries gem has had a big change that might be causing this...

specifically lib/countries/country.rb

commit here ... https://github.com/hexorx/countries/commit/a3cbddce939f9d4931b1f57df63ccc654f276c8b

**Comment by paulbeccio** [comment]
Here's my updated migration with alpha2 replacing abbr. Also had to switch the abbr and name variables for state. It was backwards for me.

    ISO3166::Country.all.each do |country_array|
      name = country_array.name
      abbr = country_array.alpha2

      country = Piggybak::Country.create :name => name, :abbr => abbr

      iso3166_country = ISO3166::Country.new(abbr)
      iso3166_country.states.each do |key, value|
        abbr = key
        name = value["name"]
        Piggybak::State.create! :name => name, :abbr => abbr, :country => country
      end
    end
  end

**Comment by marcog** [comment]
I fixed the problem by changing the migration to:
```
ISO3166::Country::Setup.data.all.each do |country_array|
  name = country_array[0]
  abbr = country_array[1]
```
