### ISSUE TITLE
Named routes error

### ISSUE THREAD

**Issue by donatoaz** [piggybak/piggybak#95]
I have just started integrating piggybak in my existing app (btw, thanks to all the developers), but I am getting an error with my named routes whenever I access any of the piggybak pages.

    undefined local variable or method `products_path' for #<#<Class:0x007ff1bf8ef3d8>:0x007ff1c18fb190>

code is in my application's layout view

    %li= link_to t('menu.all_products'), products_path if can? :manage, Product

Am i getting all this wrong and I am not supposed to used my app's named routes when using the engine actions?

Thanks again and best rgds!

**Comment by patricklewis** [comment]
Hi @donatoaz, try using `main_app.products_path` to access a named route from the parent app within the context of the Piggybak engine.

**Comment by donatoaz** [comment]
Worked like a charm. Somehow whenever I say someone mention "main_app" I thought it was like "foo_bar" and that I would have to switch to my actual app name.
